force-app/main/default/objects/AM_Investments_Profits__c/AM_Investments_Profits__c.object-meta.xml
<CustomObject>
    <label>AM Investments Profits</label>
    <nameField>
        <displayFormat>AMINV-{0000}</displayFormat>
        <label>AM In Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Investments Profits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Closing_Stock__c.field-meta.xml
<CustomField>
    <fullName>AM_Closing_Stock__c</fullName>
    <label>AM Closing Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Investment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Investment_Income__c.field-meta.xml
<CustomField>
    <fullName>AM_Investment_Income__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Investment Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Investment_Month__c.field-meta.xml
<CustomField>
    <fullName>AM_Investment_Month__c</fullName>
    <label>AM Investment Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Investment_Profits__c.field-meta.xml
<CustomField>
    <fullName>AM_Investment_Profits__c</fullName>
    <label>AM_Investment_Profits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Investment_Year__c.field-meta.xml
<CustomField>
    <fullName>AM_Investment_Year__c</fullName>
    <label>AM Investment Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AM_Investments_Profits__c/fields/AM_Opening_Stock__c.field-meta.xml
<CustomField>
    <fullName>AM_Opening_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Opening Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/AM_Vehicle_Sale__c.object-meta.xml
<CustomObject>
    <label>AM Vehicle Sale</label>
    <nameField>
        <displayFormat>AMCS-{0000}</displayFormat>
        <label>Vehicle_Sale_No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Vehicle Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Car_Id__c.field-meta.xml
<CustomField>
    <fullName>AM_Car_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM Vehicle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>AM Vehicle Sales</relationshipLabel>
    <relationshipName>AM_Car_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/Am_Price_Sold__c.field-meta.xml
<CustomField>
    <fullName>Am_Price_Sold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Am_Price_Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Profit_Gained__c.field-meta.xml
<CustomField>
    <fullName>AM_Profit_Gained__c</fullName>
    <formula>Am_Price_Sold__c - (AM_Car_Id__r.AM_Vehicle_Final_Amount__c -  AM_Car_Id__r.AM_Profit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Profit Gained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/Am_Sold_Date__c.field-meta.xml
<CustomField>
    <fullName>Am_Sold_Date__c</fullName>
    <label>Am_Sold_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Dealer_Price__c.field-meta.xml
<CustomField>
    <fullName>AM_Dealer_Price__c</fullName>
    <label>AM Dealer Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Cost__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Fuel Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Profit__c.field-meta.xml
<CustomField>
    <fullName>AM_Profit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Expected Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>AM Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Repair_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Repair_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Repair Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Final_Amount__c</fullName>
    <formula>IF(RecordType.Name==&apos;AM Owner Type&apos;, AM_Purchase_Amount__c  +  AM_Profit__c  +  AM_Repair_Amount__c + AM_Fuel_Cost__c , AM_Dealer_Price__c  +  AM_Profit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Vehicle Final Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AMInvestmentHandlerClass.cls
public class AMInvestmentHandlerClass 
{
    public static void createInvestmentProfitRecord(list<Product2> pds)
    {
        Product2 pd=new Product2();
        for(Product2 p:pds)
        {
            pd=[select id,AM_Vehicle_Final_Amount__c,RecordType.name,RecordTypeId,AM_Profit__c,AM_Purchase_Date__c 
                from Product2 
                where id=:p.id];
        }
        decimal PurchaseAmount=pd.AM_Vehicle_Final_Amount__c -pd.AM_Profit__c ;
        Integer year=pd.AM_Purchase_Date__c.year();
        Integer month=pd.AM_Purchase_Date__c.month();
        
        integer ips=[select count() from AM_Investments_Profits__c 
                     where  AM_Investment_Year__c=:year 
                     AND AM_Investment_Month__c=:month];
        
        
        list<AM_Investments_Profits__c> previp=[select AM_Investment_Month__c,AM_Opening_Stock__c,AM_Closing_Stock__c
                                                from AM_Investments_Profits__c where AM_Investment_Month__c=:month-1];
        
        AM_Investments_Profits__c ip=new AM_Investments_Profits__c();
        ip.AM_Investment_Year__c=year;
        ip.AM_Investment_Month__c=month;
        
        if(previp.size()!=0)
        {
            for(AM_Investments_Profits__c p:previp)
            {
                ip.AM_Opening_Stock__c=p.AM_Closing_Stock__c;
            }
        }
        else
        {
            for(AM_Investments_Profits__c p:previp)
            {
                ip.AM_Opening_Stock__c=0;
            }
        }
        
        if(pd.RecordType.name=='AM Owner Type')
        {
            if(ips==0)
            {
                ip.AM_Investment_Amount__c=PurchaseAmount;
                ip.AM_Closing_Stock__c=PurchaseAmount;
                ip.AM_Investment_Profits__c=0;
                insert ip;
            }
            else
            {
                AM_Investments_Profits__c ias=[select id,AM_Investment_Income__c,AM_Opening_Stock__c,AM_Closing_Stock__c,
                                               AM_Investment_Amount__c 
                                               from AM_Investments_Profits__c 
                                               where  AM_Investment_Year__c=:year 
                                               AND AM_Investment_Month__c=:month];
                
                ias.AM_Investment_Amount__c+=PurchaseAmount;
                ias.AM_Closing_Stock__c+=ias.AM_Opening_Stock__c+PurchaseAmount-0;
                update ias;
            }
        }
        else
        {
            if(ips==0)
            {
                ip.AM_Investment_Amount__c=0;
                ip.AM_Closing_Stock__c=ip.AM_Opening_Stock__c-0;
                ip.AM_Investment_Profits__c=0;
                insert ip;
            }
            else
            {
                AM_Investments_Profits__c ias=[select id,AM_Investment_Amount__c,AM_Opening_Stock__c,AM_Closing_Stock__c
                                               from AM_Investments_Profits__c 
                                               where  AM_Investment_Year__c=:year 
                                               AND AM_Investment_Month__c=:month];
                
                ias.AM_Investment_Amount__c+=0;
                ias.AM_Closing_Stock__c+=ias.AM_Opening_Stock__c-0;
                update ias;
            }
        }
    }
    public static void updateInvestmentRecord(list<AM_Vehicle_Sale__c> pds)
    {
        AM_Vehicle_Sale__c vsd=new AM_Vehicle_Sale__c();
        for(AM_Vehicle_Sale__c vs:pds)
        {
            vsd=[select id,AM_Profit_Gained__c,AM_Car_Id__c,AM_Car_Id__r.AM_Dealer_Price__c,AM_Car_Id__r.AM_Fuel_Cost__c,
                 AM_Car_Id__r.AM_Purchase_Amount__c,AM_Car_Id__r.AM_Repair_Amount__c,
                 Am_Price_Sold__c,AM_Car_Id__r.RecordType.name,Am_Sold_Date__c from 
                 AM_Vehicle_Sale__c 
                 where id=:vs.id];
        }
        Integer year=vsd.Am_Sold_Date__c.year();
        Integer month=vsd.Am_Sold_Date__c.month();
        decimal closingstock=vsd.AM_Car_Id__r.AM_Purchase_Amount__c + vsd.AM_Car_Id__r.AM_Fuel_Cost__c+vsd.AM_Car_Id__r.AM_Repair_Amount__c;
        
        integer ips=[select count() from AM_Investments_Profits__c 
                     where  AM_Investment_Year__c=:year 
                     AND AM_Investment_Month__c=:month];
        
        AM_Investments_Profits__c ip=new AM_Investments_Profits__c();
        ip.AM_Investment_Year__c=year;
        ip.AM_Investment_Month__c=month;
        
        if(vsd.AM_Car_Id__r.RecordType.name=='AM Owner Type')
        {
            if(ips==0)
            {
                ip.AM_Investment_Income__c=vsd.Am_Price_Sold__c;
                ip.AM_Closing_Stock__c=(ip.AM_Opening_Stock__c+closingstock)-vsd.Am_Price_Sold__c;
                ip.AM_Investment_Profits__c+=vsd.Am_Price_Sold__c-closingstock ;
                insert ip;
            }
            else
            {
                AM_Investments_Profits__c ias=[select id,AM_Opening_Stock__c,AM_Closing_Stock__c,AM_Investment_Income__c,AM_Investment_Profits__c
                                               from AM_Investments_Profits__c 
                                               where  AM_Investment_Year__c=:year 
                                               AND AM_Investment_Month__c=:month];
                
                ias.AM_Investment_Income__c+=vsd.Am_Price_Sold__c;
                ias.AM_Closing_Stock__c=(ias.AM_Opening_Stock__c+closingstock)- vsd.Am_Price_Sold__c ;
                ias.AM_Investment_Profits__c+=vsd.Am_Price_Sold__c-closingstock ;
                update ias;
            }
        }
        else
        {
            decimal Profit=vsd.Am_Price_Sold__c -vsd.AM_Car_Id__r.AM_Dealer_Price__c ;
            
            if(ips==0)
            {
                ip.AM_Investment_Income__c=Profit;
                ip.AM_Closing_Stock__c=ip.AM_Opening_Stock__c-Profit;
                ip.AM_Investment_Profits__c+=vsd.Am_Price_Sold__c-closingstock ;
                insert ip;
            }
            else
            {
                AM_Investments_Profits__c ias=[select id,AM_Opening_Stock__c,AM_Closing_Stock__c,AM_Investment_Income__c 
                                               from AM_Investments_Profits__c 
                                               where  AM_Investment_Year__c=:year 
                                               AND AM_Investment_Month__c=:month];
                
                ias.AM_Investment_Income__c+=Profit;
                ias.AM_Closing_Stock__c=ias.AM_Opening_Stock__c-Profit;
                ias.AM_Investment_Profits__c+=vsd.Am_Price_Sold__c-closingstock ;
                update ias;
            }
        }
    }
}