force-app/main/default/objects/AM_Vehicle_Repair_Details__c/AM_Vehicle_Repair_Details__c.object-meta.xml
<CustomObject>
    <label>AM Vehicle Repair Details</label>
    <nameField>
        <displayFormat>AMVRD-{0000}</displayFormat>
        <label>AM Vehicle  Repair Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Vehicle Repair Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Vehicle_Repair_Details__c/fields/AM_Estimated_Repair_Detail_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Estimated_Repair_Detail_Amount__c</fullName>
    <label>AM Estimated Repair Detail Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Repair_Details__c/fields/AM_Repair_Detail_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Repair_Detail_Status__c</fullName>
    <label>AM Repair Detail Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
                <default>true</default>
                <label>Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Repair_Details__c/fields/AM_Vehicle_Repair_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Repair_Type__c</fullName>
    <label>AM Vehicle Repair Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Rubbing And Polishing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Repair_Details__c/fields/AM_Vehicle_Repairs__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Repairs__c</fullName>
    <label>AM Vehicle Repairs</label>
    <referenceTo>AM_Vehicle_Repairs__c</referenceTo>
    <relationshipLabel>AM Vehicle Repair Details</relationshipLabel>
    <relationshipName>AM_Vehicle_Repair_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Repairs__c/AM_Vehicle_Repairs__c.object-meta.xml
<CustomObject>
    <label>AM Vehicle Repairs</label>
    <nameField>
        <displayFormat>AM{00000}</displayFormat>
        <label>AM Vehicle Repairs ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Vehicle Repairs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Vehicle_Repairs__c/fields/AM_Repair_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Repair_Status__c</fullName>
    <label>AM Repair Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
                <default>true</default>
                <label>Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Repairs__c/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <formula>TEXT(AM_Vehicle_Number__r.AM_Vehicle_Model__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Vehicle Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Repairs__c/fields/AM_Vehicle_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM Vehicle Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>AM Vehicle Repairs</relationshipLabel>
    <relationshipName>AM_Car_Repairs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Dealer_Price__c.field-meta.xml
<CustomField>
    <fullName>AM_Dealer_Price__c</fullName>
    <label>AM Dealer Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Cost__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Fuel Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Type__c</fullName>
    <inlineHelpText>Select any fuel type</inlineHelpText>
    <label>AM Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>LPG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Minimum_Sell_Price__c.field-meta.xml
<CustomField>
    <fullName>AM_Minimum_Sell_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Minimum Sell Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Profit__c.field-meta.xml
<CustomField>
    <fullName>AM_Profit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Expected Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>AM Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Repair_Required__c.field-meta.xml
<CustomField>
    <fullName>AM_Repair_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AM Repair Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Transmission_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Transmission_Type__c</fullName>
    <inlineHelpText>Select any Transmission Type</inlineHelpText>
    <label>AM Transmission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>IMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <inlineHelpText>Select a Color</inlineHelpText>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <inlineHelpText>Enter Car Model</inlineHelpText>
    <label>AM Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AM_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Wagon R</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Estilo</fullName>
            </value>
            <value>
                <fullName>SX4</fullName>
            </value>
            <value>
                <fullName>Swift Dzire</fullName>
            </value>
            <value>
                <fullName>A-Star</fullName>
            </value>
            <value>
                <fullName>Alto 800</fullName>
            </value>
            <value>
                <fullName>Eeco</fullName>
            </value>
            <value>
                <fullName>Ritz</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Ciaz</fullName>
            </value>
            <value>
                <fullName>Vitara Brezza</fullName>
            </value>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>EON</fullName>
            </value>
            <value>
                <fullName>i10</fullName>
            </value>
            <value>
                <fullName>Santro</fullName>
            </value>
            <value>
                <fullName>Verna</fullName>
            </value>
            <value>
                <fullName>Getz</fullName>
            </value>
            <value>
                <fullName>Allent</fullName>
            </value>
            <value>
                <fullName>Crena</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
            <value>
                <fullName>Grand i10</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Indigo</fullName>
            </value>
            <value>
                <fullName>Manza</fullName>
            </value>
            <value>
                <fullName>Vista</fullName>
            </value>
            <value>
                <fullName>Nexon</fullName>
            </value>
            <value>
                <fullName>Harrier</fullName>
            </value>
            <value>
                <fullName>Altroz</fullName>
            </value>
            <value>
                <fullName>Tiago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Registration_Date__c</fullName>
    <label>AM Vehicle Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Status__c</fullName>
    <label>AM Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Dealer-Location</fullName>
                <label>Dealer Location</label>
            </value>
            <value>
                <fullName>In-Service</fullName>
                <label>In Service</label>
            </value>
            <value>
                <fullName>In-Repair</fullName>
                <label>In Repair</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Renew Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AMVehclRepairHandlerClass_Test.cls
@isTest
private class AMVehclRepairHandlerClass_Test 
{
    @isTest
    static void TestTriggers() 
    {                
        product2 pd=new product2();
        pd.Name='AP12DQ3496';
        pd.AM_Purchase_Date__c=system.today();
        pd.AM_Vehicle_Registration_Date__c=system.today();
        pd.IsActive=true;
        pd.RecordTypeId='012Do000000YFK1';
        pd.AM_Dealer_Price__c=500000;
        pd.AM_Profit__c=20000;
        pd.AM_Minimum_Sell_Price__c=10000;
        pd.AM_Brand__c='Tata';
        pd.AM_Vehicle_Model__c='Tiago';
        pd.AM_Fuel_Type__c= 'Electric';
        pd.AM_Vehicle_Color__c= 'None';
        pd.AM_Transmission_Type__c= 'Manual';    
        pd.AM_Vehicle_Status__c='Available';   
        
        insert pd;
        
        product2 pds=new product2();
        pds.Name='AP78DQ3496';
        pds.AM_Purchase_Date__c=system.today();
        pds.AM_Vehicle_Registration_Date__c=system.today();
        pds.IsActive=true;
        pds.RecordTypeId='012Do000000YFK2';
        pds.AM_Purchase_Amount__c=600000;
        pds.AM_Fuel_Cost__c=5000;
        pds.AM_Profit__c=20000;
        pds.AM_Brand__c='Tata';
        pds.AM_Vehicle_Model__c='Tiago';
        pds.AM_Fuel_Type__c= 'Electric';
        pds.AM_Vehicle_Color__c= 'Blue';
        pds.AM_Transmission_Type__c= 'Manual';
        pds.AM_Repair_Required__c=true;
        
        insert pds;
        Product2 testpd=[select Id from Product2 where Name='AP78DQ3496'];
        
        AM_Vehicle_Repairs__c vehRep=[select id,AM_Repair_Status__c,AM_Vehicle_Number__c from AM_Vehicle_Repairs__c 
                                      where AM_Vehicle_Number__c=:testpd.Id];
        
        AM_Vehicle_Repair_Details__c vehrepdetail=new AM_Vehicle_Repair_Details__c();
        vehrepdetail.AM_Vehicle_Repairs__c=vehRep.Id;
        vehrepdetail.AM_Repair_Detail_Status__c='Progress';
        vehrepdetail.AM_Estimated_Repair_Detail_Amount__c=5000;
        vehrepdetail.AM_Vehicle_Repair_Type__c='Mechanical';
        vehrepdetail.AM_Vehicle_Repair_Sub_Type__c='Breaks';
        insert vehrepdetail;
        
        AM_Vehicle_Repair_Details__c verpdet=[select id,AM_Vehicle_Repairs__c,AM_Actual_Repair_Detail_Amount__c,AM_Estimated_Repair_Detail_Amount__c
                                              from AM_Vehicle_Repair_Details__c where AM_Vehicle_Repairs__c=:vehRep.Id];
        
        system.assertEquals(vehRep.id, verpdet.AM_Vehicle_Repairs__c);
        
        if(verpdet.AM_Actual_Repair_Detail_Amount__c==Null && verpdet.AM_Estimated_Repair_Detail_Amount__c!=Null)
        {
            verpdet.AM_Actual_Repair_Detail_Amount__c=verpdet.AM_Estimated_Repair_Detail_Amount__c;
            update verpdet;
        }
    }
}