force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Engine_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Engine_Number__c</fullName>
    <label>AM Engine Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Type__c</fullName>
    <inlineHelpText>Select any fuel type</inlineHelpText>
    <label>AM Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>LPG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <inlineHelpText>Select a Color</inlineHelpText>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <inlineHelpText>Enter Car Model</inlineHelpText>
    <label>AM Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AM_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Wagon R</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Estilo</fullName>
            </value>
            <value>
                <fullName>SX4</fullName>
            </value>
            <value>
                <fullName>Swift Dzire</fullName>
            </value>
            <value>
                <fullName>A-Star</fullName>
            </value>
            <value>
                <fullName>Alto 800</fullName>
            </value>
            <value>
                <fullName>Eeco</fullName>
            </value>
            <value>
                <fullName>Ritz</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Ciaz</fullName>
            </value>
            <value>
                <fullName>Vitara Brezza</fullName>
            </value>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>EON</fullName>
            </value>
            <value>
                <fullName>i10</fullName>
            </value>
            <value>
                <fullName>Santro</fullName>
            </value>
            <value>
                <fullName>Verna</fullName>
            </value>
            <value>
                <fullName>Getz</fullName>
            </value>
            <value>
                <fullName>Allent</fullName>
            </value>
            <value>
                <fullName>Crena</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
            <value>
                <fullName>Grand i10</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Indigo</fullName>
            </value>
            <value>
                <fullName>Manza</fullName>
            </value>
            <value>
                <fullName>Vista</fullName>
            </value>
            <value>
                <fullName>Nexon</fullName>
            </value>
            <value>
                <fullName>Harrier</fullName>
            </value>
            <value>
                <fullName>Altroz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Registration_Number__c</fullName>
    <displayFormat>VEH-{0000}</displayFormat>
    <label>AM Vehicle Identification Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/Quote_Creation_Controller.cls
global with sharing class Quote_Creation_Controller {
    public static Id quoteid;
    public static Id quoteDocId;
    public static integer i=1;
    
    @AuraEnabled
    public static id createQuoteANDQuoteLineANDQuoteDoc(id accountid, id productid){
        // Retrieving Vehicle Record
        Product2 product=[SELECT Id,Name,AM_Brand__c,AM_Vehicle_Model__c, AM_Vehicle_Color__c,
                          AM_Vehicle_Registration_Number__c,AM_Engine_Number__c,AM_Fuel_Type__c
                          FROM Product2
                          WHERE id=:productid];
        system.debug(product);
        //Retrieving Contact Record
        Contact acc=[SELECT Name,Id
                     FROM Contact 
                     WHERE id=:accountid];
        system.debug(acc);
        //Creating quote to contact
        SBQQ__Quote__c quote=new SBQQ__Quote__c();
        quote.SBQQ__Status__c='Negotiation';
        quote.SBQQ__PrimaryContact__c=acc.id;
        quote.SBQQ__Type__c='Quote';
        database.SaveResult dbs = database.insert(quote,false);
        if (dbs.isSuccess()) {
            System.debug('Quote Successfully inserted, Quote Id is: ' + dbs.getId());
            quoteid=dbs.getId();
        }
        //Creating Quote line to quote
        SBQQ__QuoteLine__c quoteline=new SBQQ__QuoteLine__c();
        quoteline.SBQQ__Quote__c=quoteid;
        quoteline.SBQQ__Product__c=productid;
        insert quoteline;
        system.debug('Quote Line Created Successfully'+quoteid);
        
        SBQQ__QuoteLine__c ql=[select id,Name From SBQQ__QuoteLine__c where SBQQ__Quote__c=:quoteid];
        system.debug('Quote Line Id: '+ql);
        //quote document creation        
        List<id> documentIds = new List<id>();
        id templateId = 'a0o5i000000NKY0AAO';
        id qId=quoteid;
        
        //  String quoteName=q.Name;
        //  String DocName=quoteName+'-'+sToday+'-'+'000'+i;
        
        id jobId = SBQQ.QuoteDocumentController.generateDocument('en_US', qId, templateId, 'DocName', 'PDF', 'Default', documentIds);
        System.debug('Job ID 1: ' + jobId);
        documentIds.add(qId);
        system.debug(qId);
        id jobId2 = SBQQ.QuoteDocumentController.saveProposal('en_US', qId, templateId, 'DocName', 'PDF', 'Default', documentIds);
        
        System.debug('Job ID 2: ' + jobId2);
        System.debug('Quote ID: ' + documentIds);
        
        
        SBQQ__Quote__c quotes=[SELECT Id,Name FROM SBQQ__Quote__c WHERE id=:qId];
        
        Datetime futureTime = Datetime.now().addSeconds(15);
        
        // Loop until the future time has been reached
        while (Datetime.now() < futureTime) 
        {
            // Do nothing, just wait
        }
        system.debug(quotes.id);
        return jobId2;
        
    }
    
    
    
}