force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Date_Of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>AM_Date_Of_Purchase__c</fullName>
    <label>AM Date Of Purchase</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>AM_Owner_Name__c</fullName>
    <label>AM Owner Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Owner_Phone__c.field-meta.xml
<CustomField>
    <fullName>AM_Owner_Phone__c</fullName>
    <label>AM Owner Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Funded_From__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Funded_From__c</fullName>
    <label>AM Purchase Funded From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>ICICI</fullName>
            </value>
            <value>
                <fullName>Home Funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Variant__c.field-meta.xml
<CustomField>
    <fullName>AM_Variant__c</fullName>
    <label>AM Variant</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <inlineHelpText>Select a Color</inlineHelpText>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Registration_Number__c</fullName>
    <displayFormat>VEH-{0000}</displayFormat>
    <label>AM Vehicle Identification Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Status__c</fullName>
    <label>AM Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Dealer-Location</fullName>
                <label>Dealer Location</label>
            </value>
            <value>
                <fullName>In-Service</fullName>
                <label>In Service</label>
            </value>
            <value>
                <fullName>In-Repair</fullName>
                <label>In Repair</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Renew Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/KMS_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMS_Travelled__c</fullName>
    <label>KMS Travelled</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PurchasedCarDetailsForManagerController.cls
public class PurchasedCarDetailsForManagerController
{
     @AuraEnabled(cacheable = true)
	public static list<Product2> purchasedCarDetails()
    {
        list<Product2> vehicle=[select Name,AM_Vehicle_Registration_Number__c,AM_Brand__c,KMS_Travelled__c,
                                AM_Date_Of_Purchase__c,AM_Purchase_Amount__c,AM_Purchase_Funded_From__c,AM_Vehicle_Color__c,
                                AM_Vehicle_Status__c,AM_Owner_Name__c,AM_Owner_Phone__c,AM_Variant__c
                                From Product2
                               ];
        system.debug(vehicle);
        return vehicle;
    }
}