force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Dealer_Price__c.field-meta.xml
<CustomField>
    <fullName>AM_Dealer_Price__c</fullName>
    <label>AM Dealer Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Cost__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Fuel Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>AM_Owner_Name__c</fullName>
    <label>AM Owner Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Owner_Phone__c.field-meta.xml
<CustomField>
    <fullName>AM_Owner_Phone__c</fullName>
    <label>AM Owner Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Profit__c.field-meta.xml
<CustomField>
    <fullName>AM_Profit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Expected Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>AM Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Funded_From__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Funded_From__c</fullName>
    <label>AM Purchase Funded From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>ICICI</fullName>
            </value>
            <value>
                <fullName>Home Funds</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <inlineHelpText>Select a Color</inlineHelpText>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <inlineHelpText>Enter Car Model</inlineHelpText>
    <label>AM Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AM_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Wagon R</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Estilo</fullName>
            </value>
            <value>
                <fullName>SX4</fullName>
            </value>
            <value>
                <fullName>Swift Dzire</fullName>
            </value>
            <value>
                <fullName>A-Star</fullName>
            </value>
            <value>
                <fullName>Alto 800</fullName>
            </value>
            <value>
                <fullName>Eeco</fullName>
            </value>
            <value>
                <fullName>Ritz</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Ciaz</fullName>
            </value>
            <value>
                <fullName>Vitara Brezza</fullName>
            </value>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>EON</fullName>
            </value>
            <value>
                <fullName>i10</fullName>
            </value>
            <value>
                <fullName>Santro</fullName>
            </value>
            <value>
                <fullName>Verna</fullName>
            </value>
            <value>
                <fullName>Getz</fullName>
            </value>
            <value>
                <fullName>Allent</fullName>
            </value>
            <value>
                <fullName>Crena</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
            <value>
                <fullName>Grand i10</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Indigo</fullName>
            </value>
            <value>
                <fullName>Manza</fullName>
            </value>
            <value>
                <fullName>Vista</fullName>
            </value>
            <value>
                <fullName>Nexon</fullName>
            </value>
            <value>
                <fullName>Harrier</fullName>
            </value>
            <value>
                <fullName>Altroz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Status__c</fullName>
    <label>AM Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Dealer-Location</fullName>
                <label>Dealer Location</label>
            </value>
            <value>
                <fullName>In-Service</fullName>
                <label>In Service</label>
            </value>
            <value>
                <fullName>In-Repair</fullName>
                <label>In Repair</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Renew Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/KMS_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMS_Travelled__c</fullName>
    <label>KMS Travelled</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PurchaseCarDetailsController_Test.cls
@isTest
public class PurchaseCarDetailsController_Test {
    // This Method is used for testing the insertion of CustomerEnquiry Details.
    @isTest
    static void testDisplayVehicleRecords() {
        // Test data setup
        Product2 testProduct = new Product2();
        testProduct.Name = 'TS08FF6803';
        testProduct.AM_Vehicle_Model__c = 'Indigo';
        testProduct.AM_Brand__c = 'Tata';
        testProduct.AM_Vehicle_Color__c = 'Red';
        testProduct.KMS_Travelled__c = '10000';
        testProduct.AM_Purchase_Date__c = Date.today();
        testProduct.AM_Purchase_Amount__c = 500000;
        testProduct.AM_Profit__c = 1000;
        testProduct.AM_Fuel_Cost__c = 400;
        testProduct.AM_Purchase_Funded_From__c = 'ICICI';
        testProduct.AM_Vehicle_Status__c = 'Available';
        testProduct.AM_Dealer_Price__c=340000;
        testProduct.AM_Owner_Name__c = 'John Doe';
        testProduct.AM_Owner_Phone__c = '1234567890';
        
        insert testProduct;
       
        Test.startTest();

        // Call the method to test
        List<Product2> results = PurchaseCarDetailsController.purchasedCarDetails1('Name','asc','Available','Tata','Indigo','500000-800000');
        
        Test.stopTest();
        
        System.assertEquals(1, results.size());
        Product2 retrievedProduct = results[0];
        System.assertEquals('TS08FF6803', retrievedProduct.Name);
        System.assertEquals('Indigo', retrievedProduct.AM_Vehicle_Model__c);
        System.assertEquals('Tata', retrievedProduct.AM_Brand__c);
        System.assertEquals('Red', retrievedProduct.AM_Vehicle_Color__c);
        System.assertEquals('10000', retrievedProduct.KMS_Travelled__c);
        System.assertEquals(Date.today(), retrievedProduct.AM_Purchase_Date__c);
        System.assertEquals(500000, retrievedProduct.AM_Purchase_Amount__c);
        System.assertEquals(1000, retrievedProduct.AM_Profit__c);
        System.assertEquals(400, retrievedProduct.AM_Fuel_Cost__c);
        System.assertEquals('ICICI', retrievedProduct.AM_Purchase_Funded_From__c);
        System.assertEquals('Available', retrievedProduct.AM_Vehicle_Status__c);
        System.assertEquals(340000, retrievedProduct.AM_Dealer_Price__c);
        System.assertEquals('John Doe', retrievedProduct.AM_Owner_Name__c);
        System.assertEquals('1234567890', retrievedProduct.AM_Owner_Phone__c);
    }
 
    @isTest
    static void testGetProductId() {
        // Test data setup
        // Create a sample product
        Product2 product = new Product2(Name = 'TS08FF6803');
        insert product;
        
        Test.startTest();        
        // Call the method to test
        Id productId = PurchaseCarDetailsController.getProductId('TS08FF6803');
        
        Test.stopTest();
        
        // Perform assertions
        System.assertEquals(product.Id, productId);
    }
}