force-app/main/default/objects/Account/fields/AM_Customer_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Customer_Aadhar_Number__c</fullName>
    <label>AM Customer Aadhar Number</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AM_Customer_Pan_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Customer_Pan_Number__c</fullName>
    <label>AM Customer Pan Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DealerquickCmpController.cls
public class DealerquickCmpController 
{
    // Method For Creating New Dealer Quick Reqistration Records
	 @AuraEnabled
    public static Id InsertDealerRec(String firstname,String lastname,string email,string company,string phone)
    {
        account accRec=new account();
        accRec.Name=lastname;
        accRec.Company__c=Company;
        accRec.Email__c=email;
        accRec.phone=phone;
        
        insert accRec;
        return accRec.Id;
    } 
    //Method For To Display Record According to the Searchterm
    
    @AuraEnabled(cacheable=true)
    public static Id searchDealer(String dealerCompany)
    {
        Account accs = new Account();
        
        if (String.isNotBlank(dealerCompany))
        {
            accs = [SELECT Id,RecordTypeId,Name,Company__c, Phone FROM Account 
                    WHERE RecordTypeId = '012Do000000YFJy' AND Company__c = :dealerCompany];
        }  
        System.debug(accs);
        return accs.Id;
    }    
     //Method For To Delete a Record According to the Searchterm
       @AuraEnabled
       public static void deleteDealer(Id dealerId)
       {
           account delacc = [Select id,Name,Company__c,Phone from account where id =:dealerId];
          delete delacc;
        }  
                  
    //Method To Display All Dealer Records
    @AuraEnabled(cacheable=true)
       public static list<Account> allDealer(String field, String sortOrder)
       {
 		String query = 'SELECT Id,RecordTypeId,Name,Phone,Email__c,Company__c,BillingAddress,AM_Customer_Aadhar_Number__c,AM_Customer_Pan_Number__c FROM Account where RecordTypeId = \'012Do000000YFJy\' ';
        if (field != null && sortOrder != null) 
        {
            query += ' ORDER BY ' + field + ' ' + sortOrder;
        }
            return Database.query(query);
       } 
}