force-app/main/default/objects/AM_Customer_Enquiry__c/AM_Customer_Enquiry__c.object-meta.xml
<CustomObject>
    <label>AM Customer Enquiry</label>
    <nameField>
        <displayFormat>AMCN-{0000}</displayFormat>
        <label>AM Customer Enquiry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Customer Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Type__c</fullName>
    <label>AM Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Transmission_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Transmission_Type__c</fullName>
    <label>AM Transmission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>IMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/KMS_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMS_Travelled__c</fullName>
    <label>KMS Travelled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-1000</fullName>
            </value>
            <value>
                <fullName>1001-5000</fullName>
            </value>
            <value>
                <fullName>5001-10000</fullName>
            </value>
            <value>
                <fullName>10001-20000</fullName>
            </value>
            <value>
                <fullName>20001-25000</fullName>
            </value>
            <value>
                <fullName>25001-30000</fullName>
            </value>
            <value>
                <fullName>30001-35000</fullName>
            </value>
            <value>
                <fullName>35001-40000</fullName>
            </value>
            <value>
                <fullName>40001-45000</fullName>
            </value>
            <value>
                <fullName>45001-50000</fullName>
            </value>
            <value>
                <fullName>50001-55000</fullName>
            </value>
            <value>
                <fullName>55001-60000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Type__c</fullName>
    <inlineHelpText>Select any fuel type</inlineHelpText>
    <label>AM Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>LPG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Transmission_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Transmission_Type__c</fullName>
    <inlineHelpText>Select any Transmission Type</inlineHelpText>
    <label>AM Transmission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>IMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Variant__c.field-meta.xml
<CustomField>
    <fullName>AM_Variant__c</fullName>
    <label>AM Variant</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <inlineHelpText>Select a Color</inlineHelpText>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <inlineHelpText>Enter Car Model</inlineHelpText>
    <label>AM Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AM_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Wagon R</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Estilo</fullName>
            </value>
            <value>
                <fullName>SX4</fullName>
            </value>
            <value>
                <fullName>Swift Dzire</fullName>
            </value>
            <value>
                <fullName>A-Star</fullName>
            </value>
            <value>
                <fullName>Alto 800</fullName>
            </value>
            <value>
                <fullName>Eeco</fullName>
            </value>
            <value>
                <fullName>Ritz</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Ciaz</fullName>
            </value>
            <value>
                <fullName>Vitara Brezza</fullName>
            </value>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>EON</fullName>
            </value>
            <value>
                <fullName>i10</fullName>
            </value>
            <value>
                <fullName>Santro</fullName>
            </value>
            <value>
                <fullName>Verna</fullName>
            </value>
            <value>
                <fullName>Getz</fullName>
            </value>
            <value>
                <fullName>Allent</fullName>
            </value>
            <value>
                <fullName>Crena</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
            <value>
                <fullName>Grand i10</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Indigo</fullName>
            </value>
            <value>
                <fullName>Manza</fullName>
            </value>
            <value>
                <fullName>Vista</fullName>
            </value>
            <value>
                <fullName>Nexon</fullName>
            </value>
            <value>
                <fullName>Harrier</fullName>
            </value>
            <value>
                <fullName>Altroz</fullName>
            </value>
            <value>
                <fullName>Tiago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Registration_Date__c</fullName>
    <label>AM Vehicle Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Status__c</fullName>
    <label>AM Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Dealer-Location</fullName>
                <label>Dealer Location</label>
            </value>
            <value>
                <fullName>In-Service</fullName>
                <label>In Service</label>
            </value>
            <value>
                <fullName>In-Repair</fullName>
                <label>In Repair</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Renew Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getsearchfilterdatacontroller_Test.cls
@isTest
private class getsearchfilterdatacontroller_Test 
{
    @isTest
    static void testGetVehicleDetails()
    {
        // Test data
        product2 pd=new product2();
        pd.Name='AP12DQ3496';
        pd.AM_Vehicle_Registration_Date__c=system.today();
        pd.IsActive=true;
        pd.RecordTypeId='012Do000000YFK1';
        pd.AM_Brand__c='Tata';
        pd.AM_Vehicle_Model__c='Tiago';
        pd.AM_Fuel_Type__c= 'Electric';
        pd.AM_Vehicle_Color__c= 'None';
        pd.AM_Transmission_Type__c= 'Manual';    
        pd.AM_Vehicle_Status__c='Available';  
        pd.AM_Variant__c='2000';
		pd.KMS_Travelled__c='45000';        
        insert pd;
        
        product2 pds=new product2();
        pds.Name='AP78DQ3496';
        pds.AM_Vehicle_Registration_Date__c=system.today();
        pds.IsActive=true;
        pds.RecordTypeId='012Do000000YFK2';
        pds.AM_Brand__c='Tata';
        pds.AM_Vehicle_Model__c='Tiago';
        pds.AM_Fuel_Type__c= 'Electric';
        pds.AM_Vehicle_Color__c= 'Blue';
        pds.AM_Transmission_Type__c= 'Manual';
        pds.AM_Vehicle_Status__c='In-Repair';   
        pds.AM_Variant__c='2000'; 
        pds.KMS_Travelled__c='6000';
        insert pds;
        // Call the method to test
        Test.startTest();
        list<Product2> results =getsearchfilterdatacontroller.getvehicledetails();
        Test.stopTest();  
        //Assertions
        System.assertEquals(2, results.size());        
    }
    @isTest
    static void testGetVehicleDetails1() 
    {
        // Create test data
             product2 p=new product2();
                p.Name='AP12DQ3476';
                p.AM_Vehicle_Registration_Date__c=system.today();
                p.IsActive=true;
                p.RecordTypeId='012Do000000YFK1';
                p.AM_Brand__c='Tata';
                p.AM_Vehicle_Model__c='Tiago';
                p.AM_Fuel_Type__c= 'Electric';
                p.AM_Vehicle_Color__c= 'Red';
                p.AM_Transmission_Type__c= 'Manual';    
                p.AM_Vehicle_Status__c='Available';  
                p.AM_Variant__c='2000';
                p.KMS_Travelled__c='45000';  
                p.AM_Make_Year__c='2021';
        		p.AM_Body_Type__c='SUV';
                insert p;

            product2 pd=new product2();
                pd.Name='AP12DQ3496';
                pd.AM_Vehicle_Registration_Date__c=system.today();
                pd.IsActive=true;
                pd.RecordTypeId='012Do000000YFK1';
                pd.AM_Brand__c='Tata';
                pd.AM_Vehicle_Model__c='Tiago';
                pd.AM_Fuel_Type__c= 'Petrol';
                pd.AM_Vehicle_Color__c= 'Red';
                pd.AM_Transmission_Type__c= 'Manual';    
                pd.AM_Vehicle_Status__c='Available';  
                pd.AM_Variant__c='2000';
                pd.KMS_Travelled__c='45000';  
                pd.AM_Make_Year__c='2020';
        		pd.AM_Body_Type__c='Sedan';
                insert pd;
       

        // Call the method to test
        Test.startTest();
        List<Product2> result = GetSearchFilterDataController.getvehicledetails1( '2020', 'Petrol', 'Sedan', 'Manual','Tata','Red', '40000-60000');
        Test.stopTest();
        // Assertions
        System.assertEquals(1, result.size());
      }
    
    @isTest
    static void testGetPreferedVehciles()
    {
          // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Phone= '9765434567'
        );
        insert testAccount;

        AM_Customer_Enquiry__c enquiry = new AM_Customer_Enquiry__c(
            AM_Brand__c = 'Tata',
            AM_Make_Year__c = '2021',
            AM_Vehicle_Color__c = 'Red',
            AM_Model__c = 'Tiago',
            AM_Fuel_Type__c = 'Petrol',
            AM_Customer__c = testAccount.Id
        );
        insert enquiry;

        List<Product2> products = new List<Product2>();
            Product2 p = new Product2();
			    p.Name='AP12DQ3476';
                p.AM_Vehicle_Registration_Date__c=system.today();
                p.IsActive=true;
                p.RecordTypeId='012Do000000YFK1';
                p.AM_Brand__c='Tata';
                p.AM_Vehicle_Model__c='Tiago';
                p.AM_Fuel_Type__c= 'Petrol';
                p.AM_Vehicle_Color__c= 'Red';
                p.AM_Transmission_Type__c= 'Manual';    
                p.AM_Vehicle_Status__c='Available';  
                p.AM_Variant__c='2000';
                p.KMS_Travelled__c='45000';  
                p.AM_Make_Year__c='2021';
        		p.AM_Body_Type__c='SUV';
                insert p;

        // Call the method to test
        Test.startTest();
        List<Product2> result = GetSearchFilterDataController.getPreferedVehciles(testAccount.Id);
        Test.stopTest();

        // Assertions
        System.assertEquals(1, result.size());
    }
       
    @isTest
    static void testSearchCustomer()
    {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Phone = '1234567890'		
        );
        insert testAccount;

        // Call the method to test
        Test.startTest();
        Id result = GetSearchFilterDataController.searchCustomer('1234567890');
        Test.stopTest();

        // Assertions
        System.assertEquals(testAccount.Id, result);
    }
    @isTest
    static void testDeleteCustomer()
    {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Phone = '1234567890'
        );
        insert testAccount;

        // Call the method to test
        Test.startTest();
        GetSearchFilterDataController.deleteCustomer(testAccount.Id);
        Test.stopTest();

        // Assertions
        List<Account> accounts = [SELECT Id FROM Account WHERE Id = :testAccount.Id];
        System.assertEquals(0, accounts.size());
    }
}