force-app/main/default/objects/AM_Customer_Enquiry__c/AM_Customer_Enquiry__c.object-meta.xml
<CustomObject>
    <label>AM Customer Enquiry</label>
    <nameField>
        <displayFormat>AMCN-{0000}</displayFormat>
        <label>AM Customer Enquiry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Customer Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Make_Year__c.field-meta.xml
<CustomField>
    <fullName>AM_Make_Year__c</fullName>
    <label>AM Make Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Model__c</fullName>
    <label>AM Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AM_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Wagon R</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Estilo</fullName>
            </value>
            <value>
                <fullName>SX4</fullName>
            </value>
            <value>
                <fullName>Swift Dzire</fullName>
            </value>
            <value>
                <fullName>A-Star</fullName>
            </value>
            <value>
                <fullName>Alto 800</fullName>
            </value>
            <value>
                <fullName>Eeco</fullName>
            </value>
            <value>
                <fullName>Ritz</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Ciaz</fullName>
            </value>
            <value>
                <fullName>Vitara Brezza</fullName>
            </value>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>i10</fullName>
            </value>
            <value>
                <fullName>EON</fullName>
            </value>
            <value>
                <fullName>Santro</fullName>
            </value>
            <value>
                <fullName>Verna</fullName>
            </value>
            <value>
                <fullName>Getz</fullName>
            </value>
            <value>
                <fullName>Allent</fullName>
            </value>
            <value>
                <fullName>Crena</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
            <value>
                <fullName>Grand i10</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Indigo</fullName>
            </value>
            <value>
                <fullName>Manza</fullName>
            </value>
            <value>
                <fullName>Vista</fullName>
            </value>
            <value>
                <fullName>Nexon</fullName>
            </value>
            <value>
                <fullName>Harrier</fullName>
            </value>
            <value>
                <fullName>Altroz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM Vehicle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>AM Customer Enquiries</relationshipLabel>
    <relationshipName>AM_Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/KMS_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMS_Travelled__c</fullName>
    <label>KMS Travelled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0-1000</fullName>
            </value>
            <value>
                <fullName>1001-5000</fullName>
            </value>
            <value>
                <fullName>5001-10000</fullName>
            </value>
            <value>
                <fullName>10001-20000</fullName>
            </value>
            <value>
                <fullName>20001-25000</fullName>
            </value>
            <value>
                <fullName>25001-30000</fullName>
            </value>
            <value>
                <fullName>30001-35000</fullName>
            </value>
            <value>
                <fullName>35001-40000</fullName>
            </value>
            <value>
                <fullName>40001-45000</fullName>
            </value>
            <value>
                <fullName>45001-50000</fullName>
            </value>
            <value>
                <fullName>50001-55000</fullName>
            </value>
            <value>
                <fullName>55001-60000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Color__c</fullName>
    <inlineHelpText>Select a Color</inlineHelpText>
    <label>AM Vehicle Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Gray</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Violet</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Maroon</fullName>
            </value>
            <value>
                <fullName>gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/KMS_Travelled__c.field-meta.xml
<CustomField>
    <fullName>KMS_Travelled__c</fullName>
    <label>KMS Travelled</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerEnquiryDetailsController.cls
public with sharing class CustomerEnquiryDetailsController 
{
    @AuraEnabled(cacheable = true)
    public static List<SObject> displayCustomerRecords()
    {
        list<AM_Customer_Enquiry__c> query=[select AM_Vehicle__r.Name,AM_Customer_Name__c,
                                            AM_Brand__c,AM_Model__c,KMS_Travelled__c,AM_Vehicle_Color__c,AM_Make_Year__c,
                                            AM_Fuel_Type__c,AM_Customer_Enquiry_Status__c,CreatedDate from AM_Customer_Enquiry__c];
          return query;
        
    }
   @AuraEnabled
    public static void deleteCustomerEnquiry(list<Id> custId) {
    list<AM_Customer_Enquiry__c> delCust =new  list<AM_Customer_Enquiry__c>() ;
         delCust = [SELECT Id, Name FROM AM_Customer_Enquiry__c WHERE Id in: custId];
        
         if(delCust != null && delCust.size()>0){
            delete delCust;
        }
       
    
}  
}