force-app/main/default/objects/AM_Customer_Enquiry__c/AM_Customer_Enquiry__c.object-meta.xml
<CustomObject>
    <label>AM Customer Enquiry</label>
    <nameField>
        <displayFormat>AMCN-{0000}</displayFormat>
        <label>AM Customer Enquiry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Customer Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Budget_Range__c.field-meta.xml
<CustomField>
    <fullName>AM_Budget_Range__c</fullName>
    <label>AM Budget Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under 3 Lakh</fullName>
            </value>
            <value>
                <fullName>3-4 Lakh</fullName>
            </value>
            <value>
                <fullName>4-5 Lakh</fullName>
            </value>
            <value>
                <fullName>5-6 Lakh</fullName>
            </value>
            <value>
                <fullName>6-8 Lakh</fullName>
            </value>
            <value>
                <fullName>8-10 Lakh</fullName>
            </value>
            <value>
                <fullName>Above 10 Lakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Customer__c.field-meta.xml
<CustomField>
    <fullName>AM_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AM Customer Enquiries</relationshipLabel>
    <relationshipName>AM_Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Customer_Enquiry_Status__c.field-meta.xml
<CustomField>
    <fullName>AM_Customer_Enquiry_Status__c</fullName>
    <label>AM Customer Enquiry Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AM_Customer_Enquiry__c/fields/AM_Vehicle_Capacity__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Capacity__c</fullName>
    <formula>TEXT(  AM_Vehicle__r.AM_Vehicle_Capacity__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Vehicle Capacity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerEnquiry.cls
public class CustomerEnquiry
{
    @AuraEnabled(cacheable = true)
    public static List<AM_Customer_Enquiry__c> getAllTable(){
       
        List<AM_Customer_Enquiry__c> accList =[select Name,AM_Brand__c,AM_Customer_Enquiry_Status__c,AM_Vehicle_Capacity__c,AM_Budget_Range__c
                                               ,AM_Customer__r.Name,AM_Customer__r.Phone,AM_Customer__r.Status,AM_Customer__r.id from  AM_Customer_Enquiry__c  ];
        
        for(AM_Customer_Enquiry__c a:accList){system.debug(a.AM_Customer__r.id);}
        return accList;
    }

}