force-app/main/default/objects/AM_Vehicle_Sale__c/AM_Vehicle_Sale__c.object-meta.xml
<CustomObject>
    <label>AM Vehicle Sale</label>
    <nameField>
        <displayFormat>AMCS-{0000}</displayFormat>
        <label>Vehicle_Sale_No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Vehicle Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <formula>TEXT( AM_Car_Id__r.AM_Brand__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Car_Id__c.field-meta.xml
<CustomField>
    <fullName>AM_Car_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM Vehicle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>AM Vehicle Sales</relationshipLabel>
    <relationshipName>AM_Car_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Model__c</fullName>
    <formula>TEXT( AM_Car_Id__r.AM_Vehicle_Model__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/Am_Price_Sold__c.field-meta.xml
<CustomField>
    <fullName>Am_Price_Sold__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Am_Price_Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Profit_Gained__c.field-meta.xml
<CustomField>
    <fullName>AM_Profit_Gained__c</fullName>
    <formula>Am_Price_Sold__c - (AM_Car_Id__r.AM_Vehicle_Final_Amount__c -  AM_Car_Id__r.AM_Profit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Profit Gained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/Am_Sold_Date__c.field-meta.xml
<CustomField>
    <fullName>Am_Sold_Date__c</fullName>
    <label>Am_Sold_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AM_Vehicle_Sale__c/fields/AM_Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Registration_Number__c</fullName>
    <formula>AM_Car_Id__r.AM_Vehicle_Registration_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Vehicle Registration Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Date_Of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>AM_Date_Of_Purchase__c</fullName>
    <label>AM Date Of Purchase</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>AM_Fuel_Type__c</fullName>
    <inlineHelpText>Select any fuel type</inlineHelpText>
    <label>AM Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>LPG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Profit__c.field-meta.xml
<CustomField>
    <fullName>AM_Profit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Expected Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Purchase_Amount__c.field-meta.xml
<CustomField>
    <fullName>AM_Purchase_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AM Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Registration_Number__c</fullName>
    <displayFormat>VEH-{0000}</displayFormat>
    <label>AM Vehicle Identification Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/CarSalesclass.cls
public with sharing class CarSalesclass {
    
    @AuraEnabled (cacheable=true)
    public static List<AM_Vehicle_Sale__c> getVehicleList(){
       

        
        List<AM_Vehicle_Sale__c> vehicleList= [SELECT Id,Am_Model__c,AM_Car_Id__r.AM_Vehicle_Registration_Number__c,
        AM_Car_Id__r.AM_Profit__c,Am_Fuel_Type__c,AM_Car_Id__r.AM_Date_Of_Purchase__c, Name,AM_Car_Id__r.AM_Purchase_Amount__c,
         AM_Car_Id__r.Name,Am_Profit_Gained__c,Am_Price_Sold__c,Am_Brand__c,sold_date__c, Am_Sold_Date__c FROM AM_Vehicle_Sale__c
        ];  
             system.debug(vehicleList.size());
        return vehicleList;


    } 
     @AuraEnabled (cacheable=true)
       public static List<AM_Vehicle_Sale__c> getbydate(Integer day, Integer month, Integer year) {
       List<AM_Vehicle_Sale__c> matchedRecords=new List<AM_Vehicle_Sale__c>();
        List<AM_Vehicle_Sale__c> matchingRecords = [SELECT Am_Model__c,AM_Car_Id__r.AM_Vehicle_Registration_Number__c,AM_Car_Id__r.AM_Purchase_Amount__c,
        AM_Car_Id__r.AM_Profit__c,Am_Fuel_Type__c,AM_Car_Id__r.AM_Date_Of_Purchase__c, Name,
         AM_Car_Id__r.Name,Am_Profit_Gained__c,Am_Price_Sold__c,Am_Brand__c, Am_Sold_Date__c FROM AM_Vehicle_Sale__c];
       for(AM_Vehicle_Sale__c a:matchingRecords){
         if(a.Am_Sold_Date__c.day()==day && a.Am_Sold_Date__c.month()==month&&a.Am_Sold_Date__c.year()==year){
               System.debug(a.Am_Sold_Date__c);
              matchedRecords.add(a);
           }
       }
       
       return matchedRecords;
    }
}