force-app/main/default/objects/AM_Vehicle_Repairs__c/AM_Vehicle_Repairs__c.object-meta.xml
<CustomObject>
    <label>AM Vehicle Repairs</label>
    <nameField>
        <displayFormat>AM{00000}</displayFormat>
        <label>AM Vehicle Repairs ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AM Vehicle Repairs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AM_Vehicle_Repairs__c/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <formula>TEXT(AM_Vehicle_Number__r.AM_Vehicle_Model__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AM Vehicle Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Brand__c.field-meta.xml
<CustomField>
    <fullName>AM_Brand__c</fullName>
    <inlineHelpText>Select a Brand</inlineHelpText>
    <label>AM Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maruti Suzuki</fullName>
            </value>
            <value>
                <fullName>Tata</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Mahindra</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Mercedes-Benz</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Volkswagen</fullName>
            </value>
            <value>
                <fullName>Renault</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AM_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>AM_Vehicle_Model__c</fullName>
    <inlineHelpText>Enter Car Model</inlineHelpText>
    <label>AM Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AM_Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alto</fullName>
            </value>
            <value>
                <fullName>Wagon R</fullName>
            </value>
            <value>
                <fullName>Swift</fullName>
            </value>
            <value>
                <fullName>Estilo</fullName>
            </value>
            <value>
                <fullName>SX4</fullName>
            </value>
            <value>
                <fullName>Swift Dzire</fullName>
            </value>
            <value>
                <fullName>A-Star</fullName>
            </value>
            <value>
                <fullName>Alto 800</fullName>
            </value>
            <value>
                <fullName>Eeco</fullName>
            </value>
            <value>
                <fullName>Ritz</fullName>
            </value>
            <value>
                <fullName>Baleno</fullName>
            </value>
            <value>
                <fullName>Ciaz</fullName>
            </value>
            <value>
                <fullName>Vitara Brezza</fullName>
            </value>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>EON</fullName>
            </value>
            <value>
                <fullName>i10</fullName>
            </value>
            <value>
                <fullName>Santro</fullName>
            </value>
            <value>
                <fullName>Verna</fullName>
            </value>
            <value>
                <fullName>Getz</fullName>
            </value>
            <value>
                <fullName>Allent</fullName>
            </value>
            <value>
                <fullName>Crena</fullName>
            </value>
            <value>
                <fullName>Venue</fullName>
            </value>
            <value>
                <fullName>Grand i10</fullName>
            </value>
            <value>
                <fullName>Polo</fullName>
            </value>
            <value>
                <fullName>Indigo</fullName>
            </value>
            <value>
                <fullName>Manza</fullName>
            </value>
            <value>
                <fullName>Vista</fullName>
            </value>
            <value>
                <fullName>Nexon</fullName>
            </value>
            <value>
                <fullName>Harrier</fullName>
            </value>
            <value>
                <fullName>Altroz</fullName>
            </value>
            <value>
                <fullName>Tiago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VehiclequickcompController_Test.cls
@isTest
class VehiclequickcompController_Test 
{
    
    @testSetup
    static void testInsertVehicleRecord() {
        // Create test data
        String vehName = 'Test Vehicle';
        String vehBrand = 'Tata';
        String vehModel = 'Tiago';
        String vehMake = '2000';
        Boolean vehRepair = true;
        Decimal vehPurAmt = 1000000.00;
        Date vehPurDate = Date.today();
        Decimal vehProfit = 50000.00;
        String vehVariant = 'Test Variant';
        Date vehRegDate = Date.today();
        Decimal vehKms = 5000.00;
        
        Test.startTest();
       Id prodId= VehiclequickcompController.insertVehicleRecord(vehName, vehBrand, vehModel, vehMake, vehRepair, vehPurAmt, vehProfit,
                                                       vehVariant, vehPurDate, vehRegDate, vehKms);
        Test.stopTest();
        
        List<Product2> insertedVehicles = [SELECT Id, Name, AM_Brand__c, AM_Vehicle_Model__c
                                           FROM Product2 WHERE Id = :prodId];
        
        System.assertEquals(1, insertedVehicles.size());
        Product2 insertedVehicle = insertedVehicles[0];
        
        System.assertEquals(vehName, insertedVehicle.Name);
        System.assertEquals(vehBrand, insertedVehicle.AM_Brand__c);
        System.assertEquals(vehModel, insertedVehicle.AM_Vehicle_Model__c);
    }
    
    
    @isTest
    static void testGotoVehicleRepairDetail()
    {
        Product2 prod = [SELECT Id FROM Product2 WHERE Name=:'Test Vehicle']; 
        Id productId = prod.Id;
        
        Test.startTest();
        id vehId=VehiclequickcompController.gotoVehicleRepairDetail(productId);
        
        Test.stopTest();
        list<AM_Vehicle_Repairs__c> vehRepair1=[Select ID from AM_Vehicle_Repairs__c
                                         where id=:vehId ];
        Integer vehrec=vehRepair1.size();
         System.assertEquals(1, vehrec);
                       
    }
    @isTest
    static void testInsertDealerVehicleRecord()
    {
		String vehName = 'Test Vehicle2';
        String vehBrand = 'Tata';
        String vehModel = 'Tiago';
        String vehMake = '2000';
        Decimal dealAmt = 1000000.00;
        Date vehPurDate = Date.today();
        Decimal vehProfit = 50000.00;
        String vehVariant = 'VDI';
        Date vehRegDate = Date.today();
        Decimal vehKms = 5000.00;    
        
        Test.startTest();
         VehiclequickcompController.insertDealerVehicleRecord(vehName,vehBrand,vehModel,vehMake,dealAmt,vehProfit,
                                                                         vehVariant,vehPurDate,vehRegDate,vehKms);
        Test.stopTest();
        List<Product2> dealVehicles = [SELECT Id, Name, AM_Brand__c, AM_Vehicle_Model__c
                                           FROM Product2 WHERE Name = :'Test Vehicle2'];
        
        System.assertEquals(1, dealVehicles.size());
        
    }
    @isTest
    static void testSearchProduct()
    {
        Product2 prod = [SELECT Id,name FROM Product2 WHERE Name=:'Test Vehicle'];
        String vehNum=prod.Name;
 		Test.startTest();
        id vehId= VehiclequickcompController.searchProduct(vehNum);
        Test.stopTest(); 
        
        List<Product2> accs= [SELECT Id, Name FROM Product2 WHERE Id = :vehId ];
        Integer pd = accs.size();
        System.assertEquals(1, pd);
    }
    
     @isTest
    static void testUpdateRepaireDetails()
    {
        Product2 prod = [SELECT Id FROM Product2 WHERE Name=:'Test Vehicle']; 
        Id productId = prod.Id;
        
        Test.startTest();
        id vehId=VehiclequickcompController.updateRepaireDetails(productId);
        
        Test.stopTest();
        list<AM_Vehicle_Repairs__c> vehRepair1=[Select ID from AM_Vehicle_Repairs__c
                                         where id=:vehId ];
        Integer vehrec=vehRepair1.size();
         System.assertEquals(1, vehrec);
    }
    
    @isTest
    static void testDeleteVehicle()
    {
        Product2 prod = [SELECT Id FROM Product2 WHERE Name=:'Test Vehicle']; 
        Id productId = prod.Id;
        
        Test.startTest();
        VehiclequickcompController.deleteVehicle(productId);
        Test.stopTest(); 
        
        List<Product2> delPro = [Select id,Name from Product2 where id =:productId];
        Integer pd = delPro.size();
        System.assertEquals(0, pd);
        
    }
}